import {
  BookOpen,
  Bus,
  ChartColumn,
  ClipboardList,
  Coffee,
  Crown,
  Flame,
  Gamepad2,
  House,
  Lightbulb,
  Medal,
  Package,
  PiggyBank,
  Receipt,
  Scale,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Soup,
  Target,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Utensils
} from "lucide-react";

const GLYPHS = {
  bag: ShoppingBag,
  book: BookOpen,
  bulb: Lightbulb,
  bus: Bus,
  cart: ShoppingCart,
  chart: ChartColumn,
  clipboard: ClipboardList,
  coffee: Coffee,
  crown: Crown,
  flame: Flame,
  gamepad: Gamepad2,
  home: House,
  medal: Medal,
  package: Package,
  piggy: PiggyBank,
  receipt: Receipt,
  scale: Scale,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sliders: SlidersHorizontal,
  soup: Soup,
  target: Target,
  trend: TrendingUp,
  trophy: Trophy,
  user: User,
  users: Users,
  utensils: Utensils,
  warn: TriangleAlert
};

export default function Glyph({ name, size = 20, ...rest }) {
  const C = GLYPHS[name] || Package;
  return <C aria-hidden="true" width={size} height={size} {...rest} />;
}